---
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: cbr1app-dev
  labels:
    app : cbr1app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: cbr1app-dev
  template:
    metadata:
      labels:
        project: cbr1app-dev   # Service looks for this label
    spec:
      containers:
        - name : cbr1app-dev
          image: umarta1/cbr-front:latest
#          imagePullPolicy: Never
#          image: umarta1/cbr-front:19
#          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
          - name: DB_HOST
            value: "dev_db_host"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "ubuntu20"
          - name: DB_NAME
            value: "mytestdb"
          resources:
            requests:
              memory: 512Mi
              cpu: 100m

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cbr1app-dev-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: cbr1app-dev
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cbr1app-dev-service
  labels:
     env  : dev
     owner: Ildar_Sharafeev
spec:
#  type: ClusterIP
  type: LoadBalancer
  selector:
    project: cbr1app-dev
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 5000  # Port on Service
      targetPort: 5000  # Port on Pod
