---
apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: cbr1app-deploy-prod
  labels:
    app : cbr1app-deploy-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      project: cbr1app-prod
  template:
    metadata:
      labels:
        project: cbr1app-prod   # Service looks for this label
    spec:
      containers:
        - name : cbr1app-prod
#          image: cbr-front:latest
          image: umarta1/cbr-front:16
#          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always   
          ports:
            - containerPort: 5000
          env:
          - name: DB_HOST
            value: "prod_db_host"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "ubuntu20"
          - name: DB_NAME
            value: "mytestdb"
          resources:
            requests:
              memory: 512Mi
              cpu: 100m

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cbr1app-prod-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: cbr1app-deploy-prod
  minReplicas: 2
  maxReplicas: 7
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cbr1app-prod-service
  labels:
     env  : prod
     owner: Ildar_Sharafeev
spec:
#  type: ClusterIP
  type: LoadBalancer
  selector:
    project: cbr1app-prod
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 5000  # Port on Service
      targetPort: 5000  # Port on Pod
